"""FABLE Calculator-specific notebook helpers for Modelwright-generated models."""

from fable_pyculator.discovery import (
    curate_default_headline_series,
    discover_output_tables,
    discover_scenario_parameters,
    discover_scenario_definition_tables,
    discover_selection_controls,
)
from fable_pyculator.spec import (
    FABLE_OUTPUT_SURFACE_SHEETS,
    FableCalculatorSpec,
    HeadlinePoint,
    HeadlineSeries,
    OutputIndicator,
    OutputTable,
    ScenarioDefinitionTable,
    ScenarioParameter,
    SelectionControl,
    SelectionOption,
)
from fable_pyculator.controls import ScenarioControlSurface
from fable_pyculator.notebook import (
    DEFAULT_2020_GENERATED_MODEL_PATH,
    DEFAULT_2020_WORKBOOK_PATH,
    DEFAULT_2021_GENERATED_MODEL_PATH,
    DEFAULT_2021_WORKBOOK_PATH,
    DEFAULT_HEADLINE_SERIES,
    DEFAULT_OUTPUT_TABLES,
    NotebookLoopResult,
    build_2021_notebook_spec,
    build_2020_notebook_spec,
    build_notebook_spec,
    load_generated_model,
    run_2021_notebook_loop,
    run_2020_notebook_loop,
    run_notebook_loop,
)
from fable_pyculator.surface import (
    ScenarioRun,
    headline_frame,
    headline_frames,
    output_table_frame,
    output_tables,
    outputs_frame,
    plot_headline,
    plot_outputs,
    run_scenario,
    scenario_definition_table_frame,
    scenario_definition_tables,
    scenario_definition_tables_for_location,
    scenario_frame,
)
from fable_pyculator.workflows import (
    DEFAULT_2021_ARTIFACT_DIR,
    DEFAULT_2021_WORKFLOW_FILENAME,
    FableFreshForgeBuildPaths,
    build_cached_workbook_validation_scenario,
    build_modelwright_freshforge_workflow,
    derive_output_refs,
    freshforge_2021_build_paths,
    write_freshforge_workflow,
    write_output_refs,
    write_validation_scenario,
)

__version__ = "0.1.0a1"

__all__ = [
    "FableCalculatorSpec",
    "FABLE_OUTPUT_SURFACE_SHEETS",
    "DEFAULT_2020_GENERATED_MODEL_PATH",
    "DEFAULT_2020_WORKBOOK_PATH",
    "DEFAULT_2021_GENERATED_MODEL_PATH",
    "DEFAULT_2021_WORKBOOK_PATH",
    "DEFAULT_2021_ARTIFACT_DIR",
    "DEFAULT_2021_WORKFLOW_FILENAME",
    "DEFAULT_HEADLINE_SERIES",
    "DEFAULT_OUTPUT_TABLES",
    "FableFreshForgeBuildPaths",
    "HeadlinePoint",
    "HeadlineSeries",
    "NotebookLoopResult",
    "OutputIndicator",
    "OutputTable",
    "ScenarioControlSurface",
    "ScenarioDefinitionTable",
    "ScenarioParameter",
    "ScenarioRun",
    "SelectionControl",
    "SelectionOption",
    "__version__",
    "build_2021_notebook_spec",
    "build_2020_notebook_spec",
    "build_cached_workbook_validation_scenario",
    "build_modelwright_freshforge_workflow",
    "build_notebook_spec",
    "curate_default_headline_series",
    "discover_output_tables",
    "discover_scenario_definition_tables",
    "discover_scenario_parameters",
    "discover_selection_controls",
    "derive_output_refs",
    "freshforge_2021_build_paths",
    "headline_frame",
    "headline_frames",
    "output_table_frame",
    "output_tables",
    "outputs_frame",
    "plot_headline",
    "plot_outputs",
    "load_generated_model",
    "run_2021_notebook_loop",
    "run_2020_notebook_loop",
    "run_notebook_loop",
    "run_scenario",
    "scenario_definition_table_frame",
    "scenario_definition_tables",
    "scenario_definition_tables_for_location",
    "scenario_frame",
    "write_freshforge_workflow",
    "write_output_refs",
    "write_validation_scenario",
]
